### ISSUE TITLE
SyntaxError: 'return' with argument inside generator

### ISSUE THREAD

**Issue by giriarteS** [darcyabjones/gi-to-tax#2]
I am using Python 2.7.10 am I got this error 

File "gi2tax.py", line 335
    return enumerate(json.load(handle))
SyntaxError: 'return' with argument inside generator

**Comment by darcyabjones** [comment]
Hi giriarteS,

I am terribly sorry for such a late reply, I didn't realise that anyone was using my software.
I'll be more diligent in checking my issues :)

This is a bug, I mixed up my use of generators and function returns.
It should be fixed with the latest push if you're still interested :)

Cheers, Darcy
