### ISSUE TITLE
Error when parsing blast table

### ISSUE THREAD

**Issue by evolgenomology** [darcyabjones/gi-to-tax#3]
Hi!

I am trying to pipe a outfmt 6 blastx table created with diamond into gi-to-tax like so:
`diamond view -a /data2/tommo-seq/lane4357_4358.clc.pe.cdhit90.vs.nr.e-5.daa |~/bioProgs/gi-to-tax/gi2tax.py -i - -d ./ -t protein -o lane4357_4358.clc.pe.cdhit90.vs.nr.e-5.taxlist --format regex
gi2tax`

And am getting this error
Using parameters:
- input file: <stdin>
- input format: regex
- taxid input path: none
- output file: lane4357_4358.clc.pe.cdhit90.vs.nr.e-5.taxlist
- database path: ./
- database contains: protein gi's

Searching for gis using regex method... Done
Found 121006 gis

Found existing SQLite database

Searching protein gi_taxid file...
Traceback (most recent call last):
  File "/home/philipp/bioProgs/gi-to-tax/gi2tax.py", line 726, in <module>
    main(*_args.**dict**)
  File "/home/philipp/bioProgs/gi-to-tax/gi2tax.py", line 523, in main
    gi_taxid_index = json.load(json_handle)
  File "/usr/lib/python3.4/json/**init**.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, *_kw)
  File "/usr/lib/python3.4/json/**init**.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

Could you help me with this please? What might be the problem?

Best regards

Philipp

**Comment by darcyabjones** [comment]
Hi Phillipp,

I'm so sorry for the late reply, I didn't realise that people were using this!
This looks to me like a problem with the json index file for `gi_taxid_prot.dmp`.

The error is coming from the built in JSON module, so probably the problem is with the file itself.
Have a look at the index file `head gi_taxid_prot.dmp` to see if the file is valid JSON (maybe it was truncated or deleted somehow).
Probably the easiest thing is to just delete the index and bear the 10 minute wait to iterate through the taxid file.

I'll update the code to check whether these indexes are parse-able shortly.

Cheers, Darcy
